src/main/java/de/_125m125/ktv2/beans/Payout.java
package de._125m125.ktv2.beans;

import java.sql.Timestamp;

import de._125m125.ktv2.Variables;
import de._125m125.ktv2.cache.Tsvable;
import de._125m125.ktv2.calculators.IDSConverter;
import de._125m125.ktv2.market.Trade.ITEM_OR_STOCK;

public class Payout extends Tsvable {
    public static enum PAYOUT_STATE {
        OPEN(true, false, false, true, false),
        FORCED(false, false, false, true, false),
        UNKNOWN(false, false, false, true, true),
        IN_PROGRESS(false, false, false, false, false),
        UNKNOWN_IN_PROGRESS(false, false, false, false, true),
        SUCCESS(false, true, true, false, false),
        SPLIT(false, true, true, false, true),
        CANCELLED(false, true, false, false, false),
        FAILED(true, false, true, false, false),
        FAILED_TAKEN(false, false, true, false, false),;

        private final boolean userInteraction;
        private final boolean success;
        private final boolean adminInteractionCompleted;
        private final boolean requiresAdminInteraction;
        private final boolean unknown;

        private PAYOUT_STATE(final boolean userInteraction, final boolean success,
                final boolean adminInteractionCompleted, final boolean requiresAdminInteraction,
                final boolean unknown) {
            this.userInteraction = userInteraction;
            this.success = success;
            this.adminInteractionCompleted = adminInteractionCompleted;
            this.requiresAdminInteraction = requiresAdminInteraction;
            this.unknown = unknown;
        }

        public static PAYOUT_STATE of(final boolean userInteraction, final boolean success,
                final boolean adminInteractionCompleted, final boolean requiresAdminInteraction,
                final boolean unknown) {
            for (final PAYOUT_STATE ps : PAYOUT_STATE.values()) {
                if (userInteraction == ps.userInteraction && success == ps.success
                        && adminInteractionCompleted == ps.adminInteractionCompleted
                        && requiresAdminInteraction == ps.requiresAdminInteraction && unknown == ps.unknown) {
                    return ps;
                }
            }
            return null;
        }

        public boolean isUserInteraction() {
            return this.userInteraction;
        }

        public boolean isSuccess() {
            return this.success;
        }

        public boolean isAdminInteractionCompleted() {
            return this.adminInteractionCompleted;
        }

        public boolean isRequiresAdminInteraction() {
            return this.requiresAdminInteraction;
        }

        public boolean isUnknown() {
            return this.unknown;
        }

    }

    public static final String  HEADER = "id\tmaterial\tmaterialName\tamount\tstate\tpayoutType\tdate\tmessage";

    private final long          id;
    private final long          uid;
    private final ITEM_OR_STOCK itemOrStock;
    private final String        material;
    private final long          amount;
    private final PAYOUT_STATE  state;
    private final Timestamp     date;
    private final String        message;

    private final String        itemName;
    private final String        payoutType;

    public Payout(final long id, final String material, final long amount, final PAYOUT_STATE state,
            final String payoutType, final Timestamp date, final String message) {
        this(id, 0, ITEM_OR_STOCK.ITEM, material, amount, state, payoutType, date, message);
    }

    public Payout(final long id, final long uid, final String material, final long amount, final PAYOUT_STATE state,
            final String payoutType, final Timestamp date, final String message) {
        this(id, uid, ITEM_OR_STOCK.ITEM, material, amount, state, payoutType, date, message);
    }

    public Payout(final long id, final long uid, final ITEM_OR_STOCK itemOrStock, final String material,
            final long amount, final PAYOUT_STATE state, final String payoutType, final Timestamp date,
            final String message) {
        super(Payout.HEADER);
        this.id = id;
        this.uid = uid;
        this.itemOrStock = itemOrStock;
        this.material = material;
        this.amount = amount;
        this.state = state;
        this.payoutType = payoutType;
        this.date = date;
        this.message = message;
        this.itemName = Variables.ID_TO_DN.get(material);
    }

    public long getId() {
        return this.id;
    }

    public long getUid() {
        return this.uid;
    }

    public String getMaterial() {
        return this.material;
    }

    public long getAmount() {
        return this.amount;
    }

    public String getStringAmount() {
        if ("-1".equals(this.material)) {
            return IDSConverter.longToDoubleString(this.amount);
        } else {
            return String.valueOf(this.amount);
        }
    }

    public PAYOUT_STATE getState() {
        return this.state;
    }

    public Timestamp getDate() {
        return this.date;
    }

    public String getMessage() {
        return this.message;
    }

    public String getItemName() {
        return this.itemName;
    }

    @Override
    public String buildTsvString() {
        final StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append(this.id);
        stringBuilder.append("\t");
        stringBuilder.append(this.material);
        stringBuilder.append("\t");
        stringBuilder.append(getItemName());
        stringBuilder.append("\t");
        stringBuilder.append((this.material.equals("-1") ? IDSConverter.longToDoubleString(this.amount) : this.amount));
        stringBuilder.append("\t");
        stringBuilder.append(Variables.translate(this.state.toString()));
        stringBuilder.append("\t");
        stringBuilder.append(this.payoutType);
        stringBuilder.append("\t");
        stringBuilder.append(this.date.getTime());
        stringBuilder.append("\t");
        stringBuilder.append(this.message);
        stringBuilder.append("\r\n");
        return stringBuilder.toString();
    }

    @Override
    public long getLastModified() {
        return this.date.getTime();
    }

    public String getPayoutType() {
        return this.payoutType;
    }

    public ITEM_OR_STOCK getItemOrStock() {
        return this.itemOrStock;
    }

    public boolean isItem() {
        return this.itemOrStock == ITEM_OR_STOCK.ITEM;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) (this.amount ^ (this.amount >>> 32));
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        result = prime * result + (int) (this.id ^ (this.id >>> 32));
        result = prime * result + ((this.itemOrStock == null) ? 0 : this.itemOrStock.hashCode());
        result = prime * result + ((this.material == null) ? 0 : this.material.hashCode());
        result = prime * result + ((this.message == null) ? 0 : this.message.hashCode());
        result = prime * result + ((this.payoutType == null) ? 0 : this.payoutType.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + (int) (this.uid ^ (this.uid >>> 32));
        return result;
    }

    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof Payout)) {
            return false;
        }
        final Payout other = (Payout) obj;
        if (this.amount != other.amount) {
            return false;
        }
        if (this.date == null) {
            if (other.date != null) {
                return false;
            }
        } else if (!this.date.equals(other.date)) {
            return false;
        }
        if (this.id != other.id) {
            return false;
        }
        if (this.itemOrStock != other.itemOrStock) {
            return false;
        }
        if (this.material == null) {
            if (other.material != null) {
                return false;
            }
        } else if (!this.material.equals(other.material)) {
            return false;
        }
        if (this.message == null) {
            if (other.message != null) {
                return false;
            }
        } else if (!this.message.equals(other.message)) {
            return false;
        }
        if (this.payoutType == null) {
            if (other.payoutType != null) {
                return false;
            }
        } else if (!this.payoutType.equals(other.payoutType)) {
            return false;
        }
        if (this.state != other.state) {
            return false;
        }
        if (this.uid != other.uid) {
            return false;
        }
        return true;
    }

}

src/main/java/de/_125m125/ktv2/servlets/admin/CouponServlet.java
package de._125m125.ktv2.servlets.admin;

import java.io.IOException;
import java.math.BigInteger;
import java.util.List;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import de._125m125.ktv2.Variables;
import de._125m125.ktv2.beans.Coupon;
import de._125m125.ktv2.calculators.PostRedirectGet;
import de._125m125.ktv2.servlets.helper.ServletHelper;

/**
 * Servlet implementation class DataServlet
 */
@WebServlet(urlPatterns = { "/admin/coupon" })
public class CouponServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    /**
     * @see HttpServlet#HttpServlet()
     */
    public CouponServlet() {
        super();
    }

    /**
     * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse
     *      response)
     */
    @Override
    protected void doGet(final HttpServletRequest request, final HttpServletResponse response)
            throws ServletException, IOException {
        final RequestDispatcher rd = request.getRequestDispatcher("/admin/coupon.jsp");
        rd.forward(request, response);
    }

    /**
     * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
     *      response)
     */
    @Override
    protected void doPost(final HttpServletRequest request, final HttpServletResponse response)
            throws ServletException, IOException {
        if (request.getParameter("create") != null) {
            createCoupons(request, response);
        }
        PostRedirectGet.execute(request, response, "create");
    }

    private void createCoupons(final HttpServletRequest request, final HttpServletResponse response)
            throws IOException {
        if (!ServletHelper.checkParams(request, "preCode", "material", "materialAmount", "couponCount")) {
            request.setAttribute("error", Variables.translate("missingParameters"));
            return;
        }
        final String preCode = request.getParameter("preCode");
        if (preCode.length() != 2 || preCode.contains("-")) {
            request.setAttribute("error", Variables.translate("invalidPreCode"));
            return;
        }
        final String material = request.getParameter("material");
        if (!Variables.resourceExists(material)) {
            request.setAttribute("error", Variables.translate("unknownMaterial"));
            return;
        }
        final String materialAmountString = request.getParameter("materialAmount");
        long materialAmount;
        try {
            materialAmount = Long.parseLong(materialAmountString);
        } catch (final NumberFormatException e) {
            request.setAttribute("error", Variables.translate("invalidAmount"));
            return;
        }
        if (materialAmount < 1) {
            request.setAttribute("error", Variables.translate("invalidAmount"));
            return;
        }
        if ("-1".equals(material)) {
            materialAmount *= 1000000;
        }

        final String couponCountString = request.getParameter("couponCount");
        int couponCount;
        try {
            couponCount = Integer.parseInt(couponCountString);
        } catch (final NumberFormatException e) {
            request.setAttribute("error", Variables.translate("invalidAmount"));
            return;
        }
        if (couponCount < 1) {
            request.setAttribute("error", Variables.translate("invalidAmount"));
            return;
        }
        final List<BigInteger> createdCoupons = Coupon.create(preCode, material, materialAmount, couponCount);
        if (createdCoupons.size() == couponCount) {
            request.setAttribute("info", Variables.translate("couponCreationSuccess"));
        } else if (createdCoupons.size() > 0) {
            request.setAttribute("error", Variables.translate("couponCreationPartialSuccess"));
        } else {
            request.setAttribute("error", Variables.translate("unknownError"));
        }
    }
}

WebContent/admin/coupon.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html lang="de">
<head>
<title>${applicationScope.appName} - Logeinsicht</title>
<link rel="stylesheet" type="text/css"
	href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.19/css/jquery.dataTables.min.css">
<jsp:include page="/c/chead.jsp" />
<!-- datatables -->
<script type="text/javascript" charset="utf8"
	src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.19/js/jquery.dataTables.min.js"></script>
</head>
<body>
	<jsp:include page="/c/top.jsp" />

	<div id="rcontent" class="col-md-12">
		<form method="POST" action="/admin/coupon" class="col-md-12">
			<fieldset>
				<legend>Neue Coupons erstellen</legend>
				<input type="hidden" name="csrfPreventionSalt"
					value="${csrfPreventionSalt}" />
				<div class="form-group-row">
					<label for="preCode" class="col-md-3 control-label">preCode</label>
					<div class="col-md-3">
						<input type="text" class="form-control" id="preCode"
							name="preCode" />
					</div>
					<label for="couponCount" class="col-md-3 control-label">Couponzahl</label>
					<div class="col-md-3">
						<input type="number" min="1" step="1" class="form-control"
							id="couponCount" name="couponCount" />
					</div>
				</div>
				<div class="form-group-row">
					<label for="material" class="col-md-3 control-label">Material</label>
					<div class="col-md-9">
						<select id="material" name="material" class="form-control"
							style="height: 34px;">
							<c:forEach var="i" items="${allItems}">
								<option value="${i[0]}"
									<c:if test="${param.item eq i[0]}">selected</c:if>><c:out
										value="${i[1]}" /></option>
							</c:forEach>
						</select>
					</div>
				</div>
				<div class="form-group-row">
					<label for="materialAmount" class="col-md-3 control-label">Materialmenge</label>
					<div class="col-md-9">
						<input type="number" min="1" step="1" class="form-control"
							id="materialAmount" name="materialAmount" />
					</div>
				</div>
				<div class="col-md-12 form-group-row">
					<input type="submit" class="btn btn-block btn-primary"
						name="create" value="Erstellen" />
				</div>
			</fieldset>
		</form>
		<table id="couponTable">
			<thead>
				<tr>
					<th>Code</th>
					<th>Material</th>
					<th>Anzahl</th>
					<th>Einlöser</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th>Code</th>
					<th>Material</th>
					<th>Anzahl</th>
					<th>Einlöser</th>
				</tr>
			</tfoot>
		</table>
	</div>
	<jsp:include page="/c/foot.jsp" />
</body>
</html>

WebContent/admin/log.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html lang="de">
<head>
<title>${applicationScope.appName} - Logeinsicht</title>
<link rel="stylesheet" type="text/css"
	href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.19/css/jquery.dataTables.min.css">
<jsp:include page="/c/chead.jsp" />
<!-- datatables -->
<script type="text/javascript" charset="utf8"
	src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.19/js/jquery.dataTables.min.js"></script>
</head>
<body>
	<jsp:include page="/c/top.jsp" />

	<div id="rcontent" class="col-md-12">
		<form class="form-horizontal">
			<div class="form-group-row">
				<label for="uid" class="col-md-2 control-label">Userid</label>
				<div class="col-md-4">
					<input type="number" min="1" step="1" class="form-control" id="uid"
						name="uid" />
				</div>
				<label for="level" class="col-md-2 control-label">Level</label>
				<div class="col-md-4">
					<input type="number" min="1" class="form-control" id="level"
						name="level" />
				</div>
			</div>
			<div class="form-group-row">
				<label for="types" class="col-md-2 control-label">Typen</label>
				<div class="col-md-10">
					<select id="types" name="types" multiple="multiple"
						class="form-control" style="width: 100%">
						<option value="br" selected="selected">Bankleser</option>
						<option value="mt" selected="selected">Fehlende
							Übersetzung</option>
						<option value="pa" selected="selected">Auszahlungen</option>
						<option value="sr">Seitenanfragen</option>
						<option value="sy" selected="selected">System</option>
						<option value="tr" selected="selected">Handel</option>
						<option value="at" selected="selected">Angriffe</option>
						<option value="ad" selected="selected">Administratoren</option>
						<option value="ws">Websocket</option>
						<option value="to" selected="selected">Token</option>
						<option value="co" selected="selected">Coupons</option>
					</select>
				</div>
			</div>
		</form>
		<table id="logTable">
			<thead>
				<tr>
					<th>id</th>
					<th>Zeit</th>
					<th>Typ</th>
					<th>Level</th>
					<th>Benutzerid</th>
					<th>Nachricht</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th>id</th>
					<th>Zeit</th>
					<th>Typ</th>
					<th>Level</th>
					<th>Benutzerid</th>
					<th>Nachricht</th>
				</tr>
			</tfoot>
		</table>
	</div>
	<jsp:include page="/c/foot.jsp" />
</body>
</html>

WebContent/admin/maintainance.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html lang="de">
<head>
<title>${applicationScope.appName} - Wartungsmodus</title>
<jsp:include page="/c/chead.jsp" />
<link
	href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css"
	rel="stylesheet" />
<script
	src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
</head>
<body>
	<jsp:include page="/c/top.jsp" />
	
	<div id="rcontent" class="col-md-12">
	<form method="POST" action="admin/maintainance" class="col-md-12">
		<fieldset>
			<legend>Wartungsmodus bearbeiten</legend>
			<input type="hidden" name="csrfPreventionSalt"
				value="${csrfPreventionSalt}" />
			<div class="form-group row">
				<div class="col-md-12">
					<div class="col-sm-6 col-md-1">
						<label><input type="checkbox" name="active"
							<c:if test="${active}">checked</c:if>>aktiv</label>
					</div>
					<div class="col-sm-6 col-md-2">
						<label><input type="checkbox" name="all"
							<c:if test="${all}">checked</c:if>>Alles sperren</label>
					</div>
					<div class="col-sm-4 col-md-3">
						<label><input type="checkbox" name="lockAdmins"
							<c:if test="${lockAdmins}">checked</c:if>>Administratoren
							sperren</label>
					</div>
					<div class="col-sm-4 col-md-3">
						<label><input type="checkbox" name="login"
							<c:if test="${login}">checked</c:if>>Loginsperre zulassen</label>
					</div>
					<div class="col-sm-4 col-md-3">
						<label><input type="checkbox" name="resources"
							<c:if test="${resources}">checked</c:if>>Resourcensperre
							zulassen</label>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-md-12">
					<input type="text" class="form-control" name="regex"
						placeholder="Regex" value="${regex}">
				</div>
			</div>
			<div class="form-group row">
				<div class="col-md-12">
					<input type="submit" class="btn btn-block btn-primary"
						name="maintSubmit" value="Änderungen sichern">
				</div>
			</div>
		</fieldset>
	</form>
	</div>
	<jsp:include page="/c/foot.jsp" />
</body>
</html>

WebContent/admin/mysqlexporter.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html lang="de">
<head>
<title>${applicationScope.appName} - MysqlExporter</title>
<jsp:include page="/c/chead.jsp" />
</head>
<body>
	<jsp:include page="/c/top.jsp" />
	
	<div id="rcontent" class="col-md-12">
	<form method="POST" action="admin/mysqlexporter" class="col-md-12">
		<fieldset>
			<legend>Daten exportieren</legend>
			<input type="hidden" name="csrfPreventionSalt"
				value="${csrfPreventionSalt}" />
			<div class="form-group row">
				<label for="uid" class="col-md-2 control-label">Userid</label>
				<div class="col-md-2">
					<input type="number" min="1" step="1" class="form-control" id="user" name="user">
				</div>
				<label for="material" class="col-md-2 control-label">Material</label>
				<div class="col-md-2">
					<input type="number" min="-10" class="form-control" id="material" name="material">
				</div>
				<div class="col-md-2">
					<label><input type="checkbox" name="anonymous">Anonymisieren</label>
				</div>
				<div class="col-md-2">
					<label><input type="checkbox" name="everything">Alle</label>
				</div>
				<div class="col-md-2">
					<label><input type="checkbox" name="usertables">Usertabellen</label>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-md-3">
					<label><input type="checkbox" name="checksums">Prüfsummen</label>
				</div>
				<div class="col-md-3">
					<c:out value="${filenames[\"checksums\"]}"></c:out>
				</div>
				<div class="col-md-3">
					<label><input type="checkbox" name="zip">Zippen</label>
				</div>
				<div class="col-md-3">
					<c:out value="${filenames[\"zip\"]}"></c:out>
				</div>
			</div>
			<c:forEach items="${tables}" var="table">
				<div class="form-group row">
					<div class="col-md-8">
						<label><input type="checkbox" name="tables" value="${table}">${table}</label>
					</div>
					<div class="col-md-4"><c:out value="${filenames[table]}"></c:out></div>
				</div>
			</c:forEach>
			<div class="form-group row">
				<div class="col-md-12">
					<input type="submit" class="btn btn-block btn-primary"
						name="generate" value="Generieren">
				</div>
			</div>
		</fieldset>
	</form>
	</div>
	<jsp:include page="/c/foot.jsp" />
</body>
</html>

WebContent/admin/payoutAdmin.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix = "fmt" uri = "http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html lang="de">
<head>
<title>${applicationScope.appName} - Adminstration - Auszahlungen</title>
<jsp:include page="/c/chead.jsp" />
<link
	href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css"
	rel="stylesheet" />
<script
	src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
</head>
<body>
	<jsp:include page="/c/top.jsp" />

	<div id="rcontent" class="col-md-12">
		<c:if test="${empty payout}">
			<p>
				Aktuelle Anzahl an offenen Auszahlungen:
				<c:out value="${totalPayoutCount}" />
			</p>
			<form method="post" action="admin/payouts">
				<input type="hidden" name="csrfPreventionSalt"
					value="${csrfPreventionSalt}" />
				<button type="submit" name="request"
					class="btn btn-primary btn-block" value="Anfordern">Neue
					Auszahlungen erhalten</button>
			</form>
		</c:if>
		<c:if test="${not empty payout}">
			<table class="table table-bordered table-hover">
				<caption>Auszahlungseinstellungen</caption>
				<thead>
					<tr>
						<th>Benutzerid</th>
						<th>Benutzername</th>
						<th>Server</th>
						<th>X</th>
						<th>Y</th>
						<th>Z</th>
						<th>Warp</th>
						<th>Karte</th>
						<th>Finde</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><c:out value="${servantId}" /></td>
						<td><c:out value="${servantName}" /></td>
						<td><c:out value="${settings.server}" /></td>
						<td><c:out value="${settings.x}" /></td>
						<td><c:out value="${settings.y}" /></td>
						<td><c:out value="${settings.z}" /></td>
						<td><c:catch var="exception"><c:out value="${settings.warp}" /></c:catch></td>
						<td><a target="_blank"
							href="http://map${settings.server}.kadcon.de/?x=${settings.x}&y=${settings.y}&z=${settings.z}&zoom=7">http://map${settings.server}.kadcon.de/?x=${settings.x}&y=${settings.y}&z=${settings.z}&zoom=7</a></td>
						<td>/finde ${settings.x},${settings.y},${settings.z}</td>
					</tr>
				</tbody>
			</table>

			<table id="payoutAdminData" class="table table-bordered table-hover">
				<caption>Auszahlungen</caption>
				<thead>
					<tr>
						<th>Besitzer</th>
						<th>TradeID</th>
						<th>Item</th>
						<th>Anzahl</th>
						<th>Status</th>
						<th>Typ</th>
						<th>Bemerkung</th>
						<th>Bearbeitungsmenge</th>
					</tr>
				</thead>
				<tbody>
					<c:forEach var="entry" items="${payout}">
						<tr>
							<td><c:out value="${entry.uid}" /></td>
							<td class="entryid"><c:out value="${entry.id}" /></td>
							<td><c:out value="${entry.itemName}" /></td>
							<td>${entry.stringAmount} (<fmt:parseNumber integerOnly="true" type="number" value="${entry.amount/64}" /> Stacks + ${entry.amount%64})</td>
							<td><c:out value="${entry.stringAmount}" /></td>
							<td><c:out value="${entry.state}" /></td>
							<td><c:out value="${entry.payoutType}" /></td>
							<td><c:out value="${entry.message}" /></td>
							<c:choose>
							<c:when test="${entry.material == '-1'}">
							<td><input class="col-md-12 modAmount" type="number" value=<c:out value="${entry.stringAmount}"/> min="0" max=<c:out value="${entry.stringAmount}"/> step="0.01"></td>
							</c:when>
							<c:otherwise>
							<td><input class="col-md-12 modAmount" type="number" value=<c:out value="${entry.amount}"/> min="0" max=<c:out value="${entry.amount}"/> step="1"></td>
							</c:otherwise>
							</c:choose>
						</tr>
					</c:forEach>
				</tbody>
			</table>
			<form id="adminPayoutEdit" method="post" action="admin/payouts">
				<fieldset>
					<legend>Auszahlungsstatus bearbeiten</legend>
					<div class="col-md-2">
						<input type="hidden" name="csrfPreventionSalt"
							value="${csrfPreventionSalt}" /> <select name="state"
							class="form-control">
							<option value="SUCCESS">Erfolgreich</option>
							<option value="FAILURE">Fehlgeschlagen</option>
							<!-- <option value="3">Offen (Bearbeitung abbrechen)</option> -->
						</select>
					</div>
					<div class="col-md-8">
						<input type="text" name="message" placeholder="Nachricht"
							maxlength="50" class="form-control" />
					</div>
					<div class="col-md-2">
						<button type="submit" name="partialUpdate"
							class="btn btn-primary btn-block" value="Status &auml;ndern">Status
							&auml;ndern</button>
					</div>
				</fieldset>
			</form>
		</c:if>
	</div>
	<jsp:include page="/c/foot.jsp" />
</body>
</html>